In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("player_advanced_stats.csv")

In [3]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,PS/G,PA/G,SRS,PER,TS%,USG%,WS,WS/48,BPM,VORP
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,106.3,99.6,6.73,13.8,0.556,15.6,6.1,0.135,0.0,1.1
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,106.3,99.6,6.73,14.2,0.534,19.9,6.6,0.120,0.9,2.0
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,106.3,99.6,6.73,14.5,0.498,18.4,1.1,0.135,-1.4,0.1
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,106.3,99.6,6.73,7.3,0.388,29.1,-0.1,-0.057,-10.3,-0.2
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,106.3,99.6,6.73,18.1,0.531,24.6,9.0,0.143,2.5,3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,103.6,103.8,-0.45,15.6,0.562,19.8,1.7,0.102,0.5,0.5
14693,14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,103.6,103.8,-0.45,1.3,0.357,14.5,0.0,-0.075,-11.2,-0.1
14694,14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,103.6,103.8,-0.45,16.1,0.515,21.4,2.3,0.086,-0.6,0.5
14695,14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,103.6,103.8,-0.45,14.0,0.558,17.8,1.3,0.113,-2.0,0.0
14696,14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,103.6,103.8,-0.45,9.7,0.603,12.1,3.4,0.071,-1.7,0.2

In [4]:
del stats["Unnamed: 0"]

In [5]:
pd.isnull(stats)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PER,TS%,USG%,WS,WS/48,BPM,VORP
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14693,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14694,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14695,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14696,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          59
3P            0
3PA           0
3P%        2086
2P            0
2PA           0
2P%         100
eFG%         59
FT            0
FTA           0
FT%         521
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
PER           3
TS%          53
USG%          3
WS            0
WS/48         3
BPM           0
VORP          0
dtype: int64

In [7]:
stats[pd.isnull(stats["TS%"])]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PER,TS%,USG%,WS,WS/48,BPM,VORP
103,Adrian Caldwell,PF,31,DAL,1,0,3.0,0.0,0.0,NaN,...,91.4,97.5,-6.33,0.0,NaN,0.0,0.0,-0.022,-5.6,0.0
250,Guy Rucker,PF,25,GSW,3,0,1.3,0.0,0.0,NaN,...,102.4,103.6,-0.60,7.8,NaN,0.0,0.0,0.117,5.6,0.0
428,Gani Lawal,PF,22,PHO,1,0,2.0,0.0,0.0,NaN,...,105.0,105.9,-0.46,-9.1,NaN,0.0,0.0,-0.009,-15.0,0.0
1172,C.J. Miles,SG,34,BOS,1,0,2.0,0.0,0.0,NaN,...,111.8,104.5,7.02,-7.8,NaN,0.0,0.0,0.030,-16.3,0.0
1850,Ade Murkey,SG,24,SAC,1,0,1.0,0.0,0.0,NaN,...,110.3,115.8,-5.26,0.0,NaN,0.0,0.0,-0.017,-9.7,0.0
2112,Ronny Turiaf,C,32,MIN,2,0,9.5,0.0,0.0,NaN,...,97.8,106.5,-8.00,4.3,NaN,0.0,0.0,0.009,-3.2,0.0
2358,DeJon Jarreau,SG,24,IND,1,0,1.0,0.0,0.0,NaN,...,111.5,114.9,-3.26,0.0,NaN,0.0,0.0,-0.022,-8.0,0.0
2411,Lari Ketner,PF,23,IND,3,0,2.3,0.0,0.0,NaN,...,92.6,92.8,-0.77,-10.6,NaN,13.3,-0.1,-0.383,-15.4,0.0
2932,Ben Moore,PF,22,IND,2,0,4.5,0.0,0.0,NaN,...,105.6,104.2,1.18,-2.3,NaN,0.0,0.0,0.072,-9.3,0.0
2947,Trey McKinney-Jones,SG,27,IND,1,0,1.0,0.0,0.0,NaN,...,105.6,104.2,1.18,0.0,NaN,0.0,0.0,-0.001,-8.5,0.0
3048,Josh Childress,SF,30,NOP,4,0,6.0,0.0,0.0,NaN,...,99.7,102.4,-1.98,3.9,NaN,1.9,0.0,-0.003,-3.3,0.0
3282,Tim Kempton,PF,32,ATL,3,0,3.7,0.0,0.0,NaN,...,98.3,97.1,1.29,-6.2,NaN,4.1,0.0,-0.060,-13.3,0.0
3343,Andy Panko,SF,23,ATL,1,0,1.0,0.0,0.0,NaN,...,91.0,96.2,-5.55,0.0,NaN,0.0,0.0,-0.017,-6.2,0.0
3362,Dickey Simpkins,PF,29,ATL,1,0,3.0,0.0,0.0,NaN,...,94.0,98.3,-4.41,11.6,NaN,0.0,0.0,0.116,14.0,0.0
3626,Jerrelle Benimon,PF,23,UTA,2,0,1.5,0.0,0.0,NaN,...,95.1,94.9,0.71,4.7,NaN,15.3,0.0,-0.215,-13.0,0.0
3736,Tyler Hall,SG,24,NYK,1,0,2.0,0.0,0.0,NaN,...,106.5,106.6,-0.01,0.0,NaN,0.0,0.0,0.007,-8.5,0.0
3942,Jordan Bell,C,27,CHI,1,0,2.0,0.0,0.0,NaN,...,111.6,112.0,-0.38,29.9,NaN,0.0,0.0,0.600,2.7,0.0
4106,Alex Scales,SG,27,SAS,1,0,0.0,0.0,0.0,NaN,...,95.6,88.8,6.69,NaN,NaN,NaN,0.0,NaN,-5.7,0.0
4370,J.P. Macura,SG,24,CLE,1,0,1.0,0.0,0.0,NaN,...,106.9,114.8,-7.77,0.0,NaN,0.0,0.0,-0.022,-6.4,0.0
4375,Marques Bolden,C,21,CLE,1,0,3.0,0.0,0.0,NaN,...,106.9,114.8,-7.77,19.8,NaN,0.0,0.0,0.282,5.4,0.0
4658,Deng Gai,C,23,PHI,2,0,2.5,0.0,0.0,NaN,...,99.4,101.3,-2.10,0.0,NaN,0.0,0.0,-0.015,-7.2,0.0
4899,Bruce Bowen,SF,25,MIA,1,0,1.0,0.0,0.0,NaN,...,94.8,89.3,5.56,37.7,NaN,0.0,0.0,0.321,97.4,0.0
5105,Billy Thompson,SF,28,GSW,1,0,1.0,0.0,0.0,NaN,...,118.7,114.8,3.77,0.0,NaN,0.0,0.0,-0.014,-6.2,0.0
5113,Mike Smrek,C,29,GSW,2,0,1.5,0.0,0.0,NaN,...,118.7,114.8,3.77,4.9,NaN,0.0,0.0,0.054,-2.6,0.0
5152,Larry Sykes,PF,22,BOS,1,0,2.0,0.0,0.0,NaN,...,103.6,107.0,-3.37,0.0,NaN,21.5,0.0,-0.397,-17.7,0.0
5456,Dwayne Jones,PF,26,PHO,2,0,3.5,0.0,0.0,NaN,...,110.2,105.3,4.67,1.4,NaN,0.0,0.0,0.045,-4.4,0.0
5521,Chris Smith,PG,26,NYK,2,0,1.0,0.0,0.0,NaN,...,98.6,99.4,-1.40,0.0,NaN,0.0,0.0,-0.020,-9.7,0.0
5879,Trevor Winter,C,25,MIN,1,0,5.0,0.0,0.0,NaN,...,92.9,92.6,-0.17,-4.3,NaN,0.0,0.0,0.202,-25.0,0.0
5988,Damion James,SF,25,BRK,2,0,0.0,0.0,0.0,NaN,...,96.9,95.1,1.25,NaN,NaN,NaN,0.0,NaN,14.0,0.0
6478,Bryon Russell,SF,35,DEN,1,0,3.0,0.0,0.0,NaN,...,100.3,100.1,0.36,16.4,NaN,0.0,0.0,0.194,8.2,0.0
6942,Brian Skinner,C,34,MIL,2,0,3.0,0.0,0.0,NaN,...,91.9,92.7,-1.02,0.0,NaN,0.0,0.0,0.023,-4.3,0.0
7243,Sam Dekker,PF,21,HOU,3,0,2.0,0.0,0.0,NaN,...,106.5,106.4,0.34,10.8,NaN,0.0,0.0,0.116,2.2,0.0
7910,John Holland,SF,30,CLE,1,0,1.0,0.0,0.0,NaN,...,104.5,114.1,-9.39,0.0,NaN,0.0,0.0,-0.032,-5.0,0.0
7913,Kobi Simmons,PG,21,CLE,1,0,2.0,0.0,0.0,NaN,...,104.5,114.1,-9.39,0.0,NaN,0.0,0.0,-0.033,-10.6,0.0
8253,Ashton Hagans,PG,21,MIN,2,0,2.0,0.0,0.0,NaN,...,112.1,117.7,-5.25,-12.4,NaN,10.5,0.0,-0.353,-21.1,0.0
8285,Cedric Hunter,PG,27,CHH,1,0,1.0,0.0,0.0,NaN,...,109.5,113.4,-3.57,0.0,NaN,0.0,0.0,-0.017,-6.3,0.0
8309,Jaime Echenique,C,24,WAS,1,0,3.0,0.0,0.0,NaN,...,108.6,112.0,-3.23,0.0,NaN,0.0,0.0,-0.012,-8.5,0.0
8662,Michael McDonald,C,28,CHH,1,0,4.0,0.0,0.0,NaN,...,96.6,94.6,2.45,-22.1,NaN,23.1,-0.1,-0.638,-32.4,0.0
9053,Steve Bardo,SG,23,SAS,1,0,1.0,0.0,0.0,NaN,...,104.0,100.6,2.81,32.3,NaN,0.0,0.0,0.424,17.1,0.0
9214,Hassan Whiteside,C,21,SAC,1,0,2.0,0.0,0.0,NaN,...,99.4,104.7,-4.80,-17.9,NaN,0.0,0.0,0.007,-27.9,0.0
9271,Tyler Ulis,PG,23,CHI,1,0,1.0,0.0,0.0,NaN,...,104.9,113.4,-8.32,0.0,NaN,0.0,0.0,-0.015,-10.4,0.0
9755,Sam Dekker,PF,27,TOR,1,0,1.0,0.0,0.0,NaN,...,109.4,107.1,2.38,0.0,NaN,0.0,0.0,0.003,-9.6,0.0
10215,Dan Godfread,C,24,HOU,1,0,2.0,0.0,0.0,NaN,...,102.0,103.7,-1.94,0.0,NaN,0.0,0.0,-0.005,-9.1,0.0
10562,JamesOn Curry,PG,24,LAC,1,0,0.0,0.0,0.0,NaN,...,95.7,102.1,-6.01,NaN,NaN,NaN,0.0,NaN,-7.0,0.0
10613,Matt Carroll,SG,32,CHA,1,0,6.0,0.0,0.0,NaN,...,93.4,102.7,-9.29,2.9,NaN,0.0,0.0,0.029,-10.0,0.0
10668,Etdrick Bohannon,SF,25,WAS,2,0,2.0,0.0,0.0,NaN,...,91.2,93.4,-1.75,0.0,NaN,0.0,0.0,-0.017,-4.6,0.0
11680,Javin DeLaurier,C,23,MIL,1,0,3.0,0.0,0.0,NaN,...,115.5,112.1,3.22,15.6,NaN,0.0,0.0,0.260,7.0,0.0
11719,Olden Polynice,C,39,LAC,2,0,6.0,0.0,0.0,NaN,...,94.8,99.4,-3.74,-9.2,NaN,14.8,-0.1,-0.394,-16.0,0.0
11827,Danuel House Jr.,SG,23,WAS,1,0,1.0,0.0,0.0,NaN,...,109.2,107.4,1.36,12.2,NaN,0.0,0.0,0.163,0.9,0.0
12967,Randell Jackson,PF,24,DAL,1,0,1.0,0.0,0.0,NaN,...,101.4,102.0,-0.29,0.0,NaN,0.0,0.0,-0.025,-6.3,0.0
13302,Jelani McCoy,C,26,CLE,2,0,6.0,0.0,0.0,NaN,...,92.9,95.5,-3.07,-3.8,NaN,3.7,0.0,-0.044,-12.7,0.0
14380,Tyler Lydon,PF,21,DEN,1,0,2.0,0.0,0.0,NaN,...,110.0,108.5,1.57,0.0,NaN,0.0,0.0,-0.014,-5.4,0.0
14461,George King,SF,25,PHO,1,0,6.0,0.0,0.0,NaN,...,107.5,116.8,-8.61,1.9,NaN,0.0,0.0,-0.001,-7.9,0.0

In [8]:
stats = stats.fillna(0)

In [9]:
pd.isnull(stats).sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
PER        0
TS%        0
USG%       0
WS         0
WS/48      0
BPM        0
VORP       0
dtype: int64

In [10]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS', 'PER', 'TS%', 'USG%', 'WS', 'WS/48', 'BPM', 'VORP'],
      dtype='object')

In [11]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 
       'L', 'W/L%', 'GB', 'PS/G','PA/G', 'SRS', 'PER', 'TS%', 'USG%', 'WS', 'WS/48',
       'BPM', 'VORP']

In [12]:
train = stats[stats["Year"] < 2022]

In [13]:
test = stats[stats["Year"] == 2022]

In [14]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [15]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [16]:
predictions = reg.predict(test[predictors])

In [17]:
predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)

In [18]:
predictions

       Predictions
648      -0.009305
649      -0.039260
650       0.002316
651       0.003582
652      -0.014656
...            ...
12508     0.006754
12509    -0.000590
12510    -0.003368
12511    -0.011751
12512     0.023029

[605 rows x 1 columns]

In [19]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [20]:
combination

                Player  Share  Predictions
648       Aaron Gordon    0.0    -0.009305
649      Austin Rivers    0.0    -0.039260
650            Bol Bol    0.0     0.002316
651       Bones Hyland    0.0     0.003582
652        Bryn Forbes    0.0    -0.014656
...                ...    ...          ...
12508     Micah Potter    0.0     0.006754
12509  Rodney McGruder    0.0    -0.000590
12510        Saben Lee    0.0    -0.003368
12511       Saddiq Bey    0.0    -0.011751
12512   Trayvon Palmer    0.0     0.023029

[605 rows x 3 columns]

In [21]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  Predictions
663             Nikola Jokić  0.875     0.241251
837              Joel Embiid  0.706     0.167494
11678  Giannis Antetokounmpo  0.595     0.221399
907             Devin Booker  0.216     0.075940
11469            Luka Dončić  0.146     0.164442
1179            Jayson Tatum  0.043     0.104396
12226              Ja Morant  0.010     0.100827
6398           Stephen Curry  0.004     0.074253
905               Chris Paul  0.002     0.056253
8241            LeBron James  0.001     0.130826

In [22]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["Predictions"])

0.0018941601453254175

In [23]:
combination["Share"].value_counts()

0.000    593
0.001      3
0.875      1
0.706      1
0.002      1
0.216      1
0.043      1
0.004      1
0.146      1
0.595      1
0.010      1
Name: Share, dtype: int64

In [24]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1,combination.shape[0]+1))

In [25]:
combination.head(10)

                      Player  Share  Predictions  Rk
663             Nikola Jokić  0.875     0.241251   1
837              Joel Embiid  0.706     0.167494   2
11678  Giannis Antetokounmpo  0.595     0.221399   3
907             Devin Booker  0.216     0.075940   4
11469            Luka Dončić  0.146     0.164442   5
1179            Jayson Tatum  0.043     0.104396   6
12226              Ja Morant  0.010     0.100827   7
6398           Stephen Curry  0.004     0.074253   8
905               Chris Paul  0.002     0.056253   9
8241            LeBron James  0.001     0.130826  10

In [26]:
combination = combination.sort_values("Predictions", ascending=False)
combination["Prediction_Rk"] = list(range(1,combination.shape[0]+1))

In [27]:
combination.head(10)

                      Player  Share  Predictions   Rk  Prediction_Rk
663             Nikola Jokić  0.875     0.241251    1              1
11678  Giannis Antetokounmpo  0.595     0.221399    3              2
837              Joel Embiid  0.706     0.167494    2              3
11469            Luka Dončić  0.146     0.164442    5              4
8241            LeBron James  0.001     0.130826   10              5
6185            Kevin Durant  0.001     0.106575   12              6
1179            Jayson Tatum  0.043     0.104396    6              7
12226              Ja Morant  0.010     0.100827    7              8
11820             Trae Young  0.000     0.096423  289              9
8276      Karl-Anthony Towns  0.000     0.091548  121             10

In [28]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  Predictions  Rk  Prediction_Rk
663             Nikola Jokić  0.875     0.241251   1              1
837              Joel Embiid  0.706     0.167494   2              3
11678  Giannis Antetokounmpo  0.595     0.221399   3              2
907             Devin Booker  0.216     0.075940   4             13
11469            Luka Dončić  0.146     0.164442   5              4
1179            Jayson Tatum  0.043     0.104396   6              7
12226              Ja Morant  0.010     0.100827   7              8
6398           Stephen Curry  0.004     0.074253   8             14
905               Chris Paul  0.002     0.056253   9             23
6185            Kevin Durant  0.001     0.106575  12              6

In [29]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("Predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [30]:
find_ap(combination)

0.876923076923077

In [31]:
years = list(range(1991, 2023))

In [32]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [33]:
sum(aps) / len(aps)

0.7781379867805955

In [34]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending=False)
    combination["Rk"] = list(range(1,combination.shape[0]+1))
    combination = combination.sort_values("Predictions", ascending=False)
    combination["Prediction_Rk"] = list(range(1,combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination["Prediction_Rk"]
    return combination

In [35]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rk"] < 6].sort_values("Diff", ascending=False)

               Player  Share  Predictions  Rk  Prediction_Rk  Diff
10976  Michael Jordan  0.832     0.248003   2              1     1
970        Grant Hill  0.327     0.220016   3              3     0
1710      Karl Malone  0.857     0.247147   1              2    -1
4912     Tim Hardaway  0.207     0.119909   4              9    -5
8642        Glen Rice  0.117     0.021612   5             77   -72

In [63]:
def backtest(stats, model, year, predictors):
    aps = []
    all_predictions = []
    
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    model.fit(train[predictors], train["Share"])
    predictions = model.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    combination = add_ranks(combination)
    all_predictions.append(combination)
    aps.append(find_ap(combination))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [37]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

ValueError: ('Lengths must match to compare', (14697,), (27,))

In [47]:
mean_ap

0.7781379867805955

In [48]:
all_predictions[all_predictions["Rk"] <= 5].sort_values("Diff").head(10)

                Player  Share  Predictions  Rk  Prediction_Rk  Diff
8642         Glen Rice  0.117     0.021612   5             77   -72
5244        Jason Kidd  0.135     0.012823   5             76   -71
8910   Peja Stojaković  0.228     0.028330   4             58   -54
5420        Steve Nash  0.839     0.037950   1             39   -38
5438        Steve Nash  0.739     0.054615   1             38   -37
1334        Jason Kidd  0.712     0.051865   2             30   -28
3849  Chauncey Billups  0.344     0.076090   5             23   -18
5453        Steve Nash  0.785     0.077906   2             19   -17
4361     Stephen Curry  0.173     0.073458   5             21   -16
1499        Chris Paul  0.138     0.055585   5             21   -16

In [49]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0      1
13  0.113939   eFG%
29  0.075034   W/L%
18  0.030849    DRB
38  0.030005  WS/48
40  0.025341   VORP
15  0.019465    FTA
16  0.018660    FT%
17  0.017197    ORB
5   0.016615    FGA
23  0.015313    TOV
10  0.008046     2P
4   0.004687     FG
24  0.004447     PF
37  0.002848     WS
31  0.000573   PS/G
30  0.000320     GB
0   0.000154    Age
26  0.000101   Year
1   0.000015      G
34 -0.000074    PER
2  -0.000180     GS
28 -0.000265      L
39 -0.000334    BPM
32 -0.000384   PA/G
27 -0.000416      W
36 -0.001024   USG%
33 -0.002436    SRS
3  -0.002718     MP
20 -0.003740    AST
22 -0.003760    BLK
8  -0.005381    3PA
9  -0.007528    3P%
25 -0.007716    PTS
7  -0.009823     3P
11 -0.011338    2PA
12 -0.013618    2P%
21 -0.015422    STL
14 -0.015676     FT
19 -0.029043    TRB
6  -0.052581    FG%
35 -0.080744    TS%

In [38]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [39]:
stat_ratios

            PTS       AST       STL       BLK        3P  Year
0      1.013334  0.420714  0.961127  0.673469  0.508587   1.0
1      1.614653  1.028412  1.647646  0.673469  4.577279   1.0
2      0.311795  0.093492  0.274608  1.571429  0.000000   1.0
3      0.200440  0.186984  0.274608  0.000000  0.000000   1.0
4      2.383005  1.636110  1.784950  0.897959  1.525760   1.0
...         ...       ...       ...       ...       ...   ...
14692  0.735752  0.819562  0.479763  1.528302  0.650951   1.0
14693  0.071202  0.000000  0.000000  0.000000  0.130190   1.0
14694  1.281633  0.601012  1.119447  2.547170  0.520761   1.0
14695  0.474679  0.218550  0.319842  1.273585  0.650951   1.0
14696  1.008693  0.655649  1.119447  0.509434  2.343424   1.0

[14697 rows x 6 columns]

In [40]:
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [41]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,USG%,WS,WS/48,BPM,VORP,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,15.6,6.1,0.135,0.0,1.1,1.013334,0.420714,0.961127,0.673469,0.508587
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,19.9,6.6,0.120,0.9,2.0,1.614653,1.028412,1.647646,0.673469,4.577279
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,18.4,1.1,0.135,-1.4,0.1,0.311795,0.093492,0.274608,1.571429,0.000000
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,29.1,-0.1,-0.057,-10.3,-0.2,0.200440,0.186984,0.274608,0.000000,0.000000
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,24.6,9.0,0.143,2.5,3.4,2.383005,1.636110,1.784950,0.897959,1.525760

In [42]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [43]:
mean_ap, aps, all_predictions = backtest(stats, reg, 2018, predictors)

In [44]:
mean_ap

0.9266666666666665

In [45]:
all_predictions.head(15)

                      Player  Share  Predictions   Rk  Prediction_Rk  Diff
7895            LeBron James  0.731     0.221694    2              1     1
929             James Harden  0.955     0.182587    1              2    -1
6666       Russell Westbrook  0.075     0.171006    5              3     2
12383  Giannis Antetokounmpo  0.074     0.134555    6              4     2
3102          Damian Lillard  0.205     0.127645    4              5    -1
8212           Anthony Davis  0.441     0.109480    3              6    -3
6337            Kevin Durant  0.065     0.108936    7              7     0
14375           Nikola Jokić  0.000     0.102524  184              8   176
5694             Ben Simmons  0.000     0.095796  427              9   418
2948          Victor Oladipo  0.002     0.095296   13             10     3
1454            Kyrie Irving  0.000     0.094367  291             11   280
524       Karl-Anthony Towns  0.000     0.090613  366             12   354
4336              Kyle Lowry  0.000     0.077614  521             13   508
14002           Kemba Walker  0.000     0.074669  154             14   140
4331           DeMar DeRozan  0.032     0.070861    8             15    -7

In [125]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 100, random_state=1, min_samples_split=5)

In [136]:
mean_ap, aps, all_predictions = backtest(stats, rf, 2005, predictors)

In [66]:
mean_ap

0.8083333333333332

In [137]:
all_predictions.head(30)

                  Player  Share  Predictions   Rk  Prediction_Rk  Diff
8118       Kevin Garnett  0.012     0.539979   11              1    10
5410   Amar'e Stoudemire  0.032     0.421192   10              2     8
3416       Dirk Nowitzki  0.275     0.395577    3              3     0
5741        LeBron James  0.073     0.362763    6              4     2
10750         Tim Duncan  0.258     0.200649    4              5    -1
1093       Allen Iverson  0.189     0.190044    5              6    -1
4992    Shaquille O'Neal  0.813     0.189556    2              7    -5
4985         Dwyane Wade  0.034     0.182794    8              8     0
12681        Kobe Bryant  0.000     0.119818  176              9   167
11424      Tracy McGrady  0.035     0.115183    7             10    -3
5420          Steve Nash  0.839     0.096979    1             11   -10
11726     Corey Maggette  0.000     0.096104  138             12   126
5418        Shawn Marion  0.001     0.077444   14             13     1
8474     Jermaine O'Neal  0.000     0.057021   63             14    49
8478   Metta World Peace  0.000     0.055187   33             15    18
9342           Ray Allen  0.032     0.039120    9             16    -7
7853      Gilbert Arenas  0.003     0.037552   12             17    -5
10315       Vince Carter  0.002     0.024284   13             18    -5
1095        Chris Webber  0.000     0.020271  321             19   302
2776         Paul Pierce  0.000     0.017379  243             20   223
10744      Manu Ginóbili  0.000     0.013988  197             21   176
4588     Stephon Marbury  0.000     0.012393  452             22   430
3795    Andrei Kirilenko  0.000     0.012017  281             23   258
11728        Elton Brand  0.000     0.011287  123             24    99
7859        Larry Hughes  0.000     0.010328   80             25    55
10311  Richard Jefferson  0.000     0.005264  122             26    96
11426           Yao Ming  0.000     0.002791  215             27   188
10308         Jason Kidd  0.000     0.002064   38             28    10
6016       Steve Francis  0.000     0.001608  382             29   353
9605    Chauncey Billups  0.000     0.001294   57             30    27