In [1]:
import pandas as pd

In [7]:
stats = pd.read_csv("player_advanced_stats.csv")

In [8]:
del stats["Unnamed: 0"]

In [9]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          59
3P            0
3PA           0
3P%        2086
2P            0
2PA           0
2P%         100
eFG%         59
FT            0
FTA           0
FT%         521
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
PER           3
TS%          53
USG%          3
WS            0
WS/48         3
BPM           0
VORP          0
dtype: int64

In [10]:
stats = stats.fillna(0)

In [11]:
pd.isnull(stats).sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
PER        0
TS%        0
USG%       0
WS         0
WS/48      0
BPM        0
VORP       0
dtype: int64

In [12]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS', 'PER', 'TS%', 'USG%', 'WS', 'WS/48', 'BPM', 'VORP'],
      dtype='object')

In [13]:
stats_2023 = pd.read_csv("player_team_2023.csv")

In [15]:
del stats_2023["Unnamed: 0"]

In [16]:
pd.isnull(stats_2023).sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        2
3P         0
3PA        0
3P%       16
2P         0
2PA        0
2P%        5
eFG%       2
FT         0
FTA        0
FT%       24
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
PER        0
TS%        2
USG%       0
WS         0
WS/48      0
BPM        0
VORP       0
dtype: int64

In [17]:
stats_2023 = stats_2023.fillna(0)

In [18]:
pd.isnull(stats_2023).sum()

Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
Year      0
Team      0
W         0
L         0
W/L%      0
GB        0
PS/G      0
PA/G      0
SRS       0
PER       0
TS%       0
USG%      0
WS        0
WS/48     0
BPM       0
VORP      0
dtype: int64

In [19]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 
       'L', 'W/L%', 'GB', 'PS/G','PA/G', 'SRS', 'PER', 'TS%', 'USG%', 'WS', 'WS/48',
       'BPM', 'VORP']

In [22]:
stats_2023["Year"]

0      2023
1      2023
2      2023
3      2023
4      2023
       ...
534    2023
535    2023
536    2023
537    2023
538    2023
Name: Year, Length: 539, dtype: int64

In [20]:
train = stats[stats["Year"] < 2023]

In [23]:
test = stats_2023[stats_2023["Year"] == 2023]

In [24]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [25]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [26]:
predictions = reg.predict(test[predictors])

In [27]:
predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)

In [28]:
combination = pd.concat([test["Player"], predictions], axis=1)

In [29]:
combination

                    Player  Predictions
0               A.J. Green     0.013929
1             Bobby Portis     0.022201
2              Brook Lopez     0.032943
3    Giannis Antetokounmpo     0.215360
4             Goran Dragić    -0.004659
..                     ...          ...
534      Mitchell Robinson    -0.015124
535             Obi Toppin     0.008597
536         Quentin Grimes    -0.015375
537             RJ Barrett    -0.020023
538           Trevor Keels     0.011731

[539 rows x 2 columns]

In [30]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
3      Giannis Antetokounmpo     0.215360
67              Nikola Jokić     0.208405
31               Luka Dončić     0.183838
515              Joel Embiid     0.168763
105  Shai Gilgeous-Alexander     0.124707
184         Domantas Sabonis     0.120833
130             Jayson Tatum     0.115372
318             LeBron James     0.105053
405                Ja Morant     0.103995
532            Julius Randle     0.101969

In [31]:
combination = combination.sort_values("Predictions", ascending=False)
combination["Prediction_Rk"] = list(range(1,combination.shape[0]+1))

In [32]:
combination.head(10)

                      Player  Predictions  Prediction_Rk
3      Giannis Antetokounmpo     0.215360              1
67              Nikola Jokić     0.208405              2
31               Luka Dončić     0.183838              3
515              Joel Embiid     0.168763              4
105  Shai Gilgeous-Alexander     0.124707              5
184         Domantas Sabonis     0.120833              6
130             Jayson Tatum     0.115372              7
318             LeBron James     0.105053              8
405                Ja Morant     0.103995              9
532            Julius Randle     0.101969             10

In [33]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [34]:
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [35]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,USG%,WS,WS/48,BPM,VORP,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,15.6,6.1,0.135,0.0,1.1,1.013334,0.420714,0.961127,0.673469,0.508587
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,19.9,6.6,0.120,0.9,2.0,1.614653,1.028412,1.647646,0.673469,4.577279
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,18.4,1.1,0.135,-1.4,0.1,0.311795,0.093492,0.274608,1.571429,0.000000
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,29.1,-0.1,-0.057,-10.3,-0.2,0.200440,0.186984,0.274608,0.000000,0.000000
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,24.6,9.0,0.143,2.5,3.4,2.383005,1.636110,1.784950,0.897959,1.525760

In [36]:
stat_ratios = stats_2023[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [37]:
stats_2023[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [38]:
stats_2023.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,USG%,WS,WS/48,BPM,VORP,PTS_R,AST_R,STL_R,BLK_R,3P_R
0,A.J. Green,SG,23,MIL,35,1,9.9,1.5,3.6,0.424,...,16.6,0.8,0.111,-0.9,0.1,0.482405,0.290045,0.328058,0.000000,1.312664
1,Bobby Portis,PF,27,MIL,70,22,26.0,5.7,11.5,0.496,...,21.7,5.3,0.139,0.7,1.2,1.545889,0.725112,0.656117,0.523301,1.413638
2,Brook Lopez,C,34,MIL,78,78,30.4,6.1,11.5,0.531,...,19.3,8.0,0.161,2.1,2.5,1.743237,0.628430,0.820146,6.541262,1.716561
3,Giannis Antetokounmpo,PF,28,MIL,63,63,32.1,11.2,20.3,0.553,...,38.8,8.6,0.204,8.5,5.4,3.409727,2.755426,1.312234,2.093204,0.706819
4,Goran Dragić,PG,36,MIL,58,0,15.0,2.4,5.8,0.421,...,21.1,0.4,0.025,-3.9,-0.4,0.690716,1.256861,0.328058,0.261650,0.908767

In [39]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [46]:
year = 2023

In [47]:
train = stats[stats["Year"] < year]
test = stats_2023[stats_2023["Year"] == year]

In [48]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [49]:
predictions = reg.predict(test[predictors])

In [50]:
predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)

In [51]:
combination = pd.concat([test["Player"], predictions], axis=1)

In [52]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
3      Giannis Antetokounmpo     0.202713
67              Nikola Jokić     0.197917
31               Luka Dončić     0.183892
515              Joel Embiid     0.153781
130             Jayson Tatum     0.119469
105  Shai Gilgeous-Alexander     0.114398
184         Domantas Sabonis     0.111258
532            Julius Randle     0.107543
318             LeBron James     0.103770
405                Ja Morant     0.098358

In [55]:
year = 2023

train = stats[stats["Year"] < year]
test = stats_2023[stats_2023["Year"] == year]

reg.fit(train[predictors], train["Share"])
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
combination = pd.concat([test["Player"], predictions], axis=1)

In [56]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
3      Giannis Antetokounmpo     0.202713
67              Nikola Jokić     0.197917
31               Luka Dončić     0.183892
515              Joel Embiid     0.153781
130             Jayson Tatum     0.119469
105  Shai Gilgeous-Alexander     0.114398
184         Domantas Sabonis     0.111258
532            Julius Randle     0.107543
318             LeBron James     0.103770
405                Ja Morant     0.098358

In [63]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 500, random_state=1, min_samples_split=5)

In [64]:
year = 2023

train = stats[stats["Year"] < year]
test = stats_2023[stats_2023["Year"] == year]

rf.fit(train[predictors], train["Share"])
predictions = rf.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["Predictions"], index=test.index)
combination = pd.concat([test["Player"], predictions], axis=1)

N_estimator = 100

In [59]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
67              Nikola Jokić     0.600235
515              Joel Embiid     0.482979
3      Giannis Antetokounmpo     0.425595
31               Luka Dončić     0.362915
374             Jimmy Butler     0.189020
130             Jayson Tatum     0.183180
105  Shai Gilgeous-Alexander     0.173223
184         Domantas Sabonis     0.101442
292           Damian Lillard     0.089879
457         Donovan Mitchell     0.052695

N_estimator = 200

In [62]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
67              Nikola Jokić     0.574677
515              Joel Embiid     0.502165
3      Giannis Antetokounmpo     0.408487
31               Luka Dončić     0.389961
105  Shai Gilgeous-Alexander     0.191946
130             Jayson Tatum     0.190742
374             Jimmy Butler     0.179462
184         Domantas Sabonis     0.108632
292           Damian Lillard     0.070864
457         Donovan Mitchell     0.060579

In [65]:
combination.sort_values("Predictions", ascending=False).head(10)

                      Player  Predictions
67              Nikola Jokić     0.560734
515              Joel Embiid     0.506704
3      Giannis Antetokounmpo     0.406133
31               Luka Dončić     0.378446
105  Shai Gilgeous-Alexander     0.200816
130             Jayson Tatum     0.198497
374             Jimmy Butler     0.169445
184         Domantas Sabonis     0.117040
292           Damian Lillard     0.081891
457         Donovan Mitchell     0.068717